name: Build
on:
  push:
    branches: [master]
    tags:
      - '*.*.*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  fetch-version:
    uses: ./.github/workflows/reusable_fetch_version.yaml 

  build-docker:
    needs: fetch-version
    uses: ./.github/workflows/reusable_build_docker.yaml
    with:
      arch: x86_64
      version: ${{ needs.fetch-version.outputs.version }}
      tag: master
    secrets: inherit

  build-docker-arm64:
    needs: fetch-version
    uses: ./.github/workflows/reusable_build_docker.yaml
    with:
      arch: aarch64
      version: ${{ needs.fetch-version.outputs.version }}
      tag: master
    secrets: inherit

  publish-docker:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    needs: [build-docker, build-docker-arm64]
    uses: ./.github/workflows/reusable_publish_docker.yaml
    with:
      # We don't do backports.
      is_latest: true
      tag: ${{ github.event.ref }}
    secrets: inherit
