name: Dev Packages and Docker images
on:
  push:
    branches: [master]

# Checks if any concurrent jobs is running for master CI and eventually cancel it
concurrency:
  group: ci-master
  cancel-in-progress: true

jobs:
  fetch-version:
    uses: ./.github/workflows/reusable_fetch_version.yaml 

  build-dev-docker:
    needs: fetch-version
    uses: ./.github/workflows/reusable_build_docker.yaml
    with:
      arch: x86_64
      version: ${{ needs.fetch-version.outputs.version }}
      tag: master
    secrets: inherit

  build-dev-docker-arm64:
    needs: fetch-version
    uses: ./.github/workflows/reusable_build_docker.yaml
    with:
      arch: aarch64
      version: ${{ needs.fetch-version.outputs.version }}
      tag: master
    secrets: inherit
